framework:
    messenger:


        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration

            sync: 'sync://'

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: sync
            Symfony\Component\Notifier\Message\ChatMessage: sync
            Symfony\Component\Notifier\Message\SmsMessage: sync

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
