vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
            user:
                uri_prefix: /assets/img/user
                upload_destination: '%kernel.project_dir%/public/assets/img/user'
                namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

                inject_on_load: false
                delete_on_update: false
                delete_on_remove: false

            news:
                uri_prefix: /assets/img/news
                upload_destination: '%kernel.project_dir%/public/assets/img/news'
                namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

                inject_on_load: false
                delete_on_update: false
                delete_on_remove: false

            spectacles:
                uri_prefix: /assets/img/spectacles
                upload_destination: '%kernel.project_dir%/public/assets/img/spectacles'
                namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

                inject_on_load: false
                delete_on_update: false
                delete_on_remove: false

            actors:
                uri_prefix: /assets/img/actors
                upload_destination: '%kernel.project_dir%/public/assets/img/actors'
                namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

                inject_on_load: false
                delete_on_update: false
                delete_on_remove: false

            slider:
                uri_prefix: /assets/img/slider
                upload_destination: '%kernel.project_dir%/public/assets/img/slider'
                namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

                inject_on_load: false
                delete_on_update: false
                delete_on_remove: false