vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        user:
            uri_prefix: /assets/img/user
            upload_destination: '%kernel.project_dir%/public/assets/img/user'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true